version: '3'
services:
  golarm:
    build:
      context: .
    container_name: "golarm"
    ports:
      - "8787:8787"
    environment: 
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - "golarm-net"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"
    networks:
      - "golarm-net"

volumes:
   mongo-data:

networks:
   golarm-net: